"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type View = "overview" | "commercial" | "projects" | "data" | "reports" | "settings";
type Project = { id: string; name: string; client: string; progress: number; margin: number; team: number };
type ActionPlan = { id: string; title: string; detail: string; done: boolean; createdAt: string };
type PeriodRecord = { period: string; revenue: number; previousRevenue: number; target: number; margin: number; pipeline: number; utilization: number; proposals: number; negotiations: number; closings: number; projects: Project[] };
type DashboardData = {
  company: string; owner: string; period: string; revenue: number; previousRevenue: number; target: number;
  margin: number; pipeline: number; utilization: number; proposals: number; negotiations: number; closings: number;
  marginTarget: number; utilizationTarget: number; currency: "BRL"; projects: Project[]; actions: ActionPlan[]; periods: PeriodRecord[];
  segment: string; notificationEmail: string; reportNote: string;
};

const defaultProjects: Project[] = [
  { id: "atlas", name: "Projeto Atlas", client: "Northstar Health", progress: 64, margin: 24, team: 8 },
  { id: "prisma", name: "Operação Prisma", client: "Vértice Capital", progress: 82, margin: 38, team: 5 },
  { id: "horizon", name: "Programa Horizon", client: "Lumina Retail", progress: 46, margin: 34, team: 6 },
  { id: "core", name: "Transformação Core", client: "Arco Logística", progress: 29, margin: 27, team: 4 },
];
const defaults: DashboardData = {
  company: "Lumina Consultoria", owner: "Luan Moroni", period: "Julho 2026", revenue: 284000, previousRevenue: 252600,
  target: 310000, margin: 31.8, pipeline: 620000, utilization: 78, proposals: 18, negotiations: 9, closings: 4,
  marginTarget: 30, utilizationTarget: 82, currency: "BRL", projects: defaultProjects, actions: [], periods: [],
  segment: "Serviços e consultoria", notificationEmail: "", reportNote: "Documento confidencial para uso interno.",
};

const normalise = (value: Partial<DashboardData> | null): DashboardData => ({
  ...defaults, ...(value || {}), projects: value?.projects?.length ? value.projects : defaultProjects, actions: value?.actions || [], periods: value?.periods || [],
});
const toPeriodRecord = (data: DashboardData): PeriodRecord => ({ period:data.period,revenue:data.revenue,previousRevenue:data.previousRevenue,target:data.target,margin:data.margin,pipeline:data.pipeline,utilization:data.utilization,proposals:data.proposals,negotiations:data.negotiations,closings:data.closings,projects:data.projects });
const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 }).format(value || 0);
const compactMoney = (value: number) => value >= 1_000_000 ? `R$ ${(value / 1_000_000).toFixed(2).replace(".", ",")} mi` : `R$ ${Math.round((value || 0) / 1000)} mil`;
const pct = (value: number) => Number.isFinite(value) ? `${value.toFixed(1).replace(".", ",")}%` : "Dados inválidos";
const clamp = (value: number, min = 0, max = 100) => Math.min(Math.max(value || 0, min), max);

function projectHealth(project: Project, marginTarget: number) {
  if (project.margin < marginTarget * .85 || (project.progress < 40 && project.team < 5)) return { label: "Atenção", tone: "warn" };
  if (project.margin < marginTarget || project.progress < 50) return { label: "Monitorar", tone: "neutral" };
  return { label: "Saudável", tone: "good" };
}
function recommendationFor(data: DashboardData) {
  const risky = data.projects.filter(p => projectHealth(p, data.marginTarget).tone === "warn").sort((a,b) => a.margin - b.margin)[0];
  const conversion = data.proposals ? data.closings / data.proposals * 100 : 0;
  if (data.negotiations > data.proposals || data.closings > data.negotiations) return { title: "Corrigir os dados do funil comercial.", detail: "Há etapas com volume superior à etapa anterior. Revise a entrada de dados antes de decidir.", impact: "Dados confiáveis" };
  if (risky) return { title: `Revisar capacidade e margem de ${risky.name}.`, detail: `${risky.client}: margem de ${pct(risky.margin)} e ${pct(risky.progress)} de progresso. Defina responsável e ação corretiva.`, impact: `${money(Math.max((data.marginTarget-risky.margin)/100*data.revenue,0))} em risco` };
  if (data.revenue < data.target && conversion < 25) return { title: "Acelerar negociações com maior probabilidade.", detail: `Faltam ${compactMoney(data.target-data.revenue)} para a meta e a conversão está em ${pct(conversion)}. Priorize propostas qualificadas.`, impact: `${compactMoney(data.target-data.revenue)} para a meta` };
  if (data.utilization < data.utilizationTarget) return { title: "Redistribuir a capacidade disponível.", detail: `A utilização está em ${pct(data.utilization)}, abaixo da meta de ${pct(data.utilizationTarget)}. Antecipe entregas ou apoie o comercial.`, impact: `${pct(data.utilizationTarget-data.utilization)} de capacidade` };
  return { title: "Proteger o ritmo atual e preparar o próximo ciclo.", detail: "Os principais indicadores estão dentro das metas. Revise pipeline e capacidade para sustentar o desempenho.", impact: "Metas protegidas" };
}

export function Dashboard() {
  const [view, setView] = useState<View>("overview");
  const [data, setData] = useState<DashboardData>(defaults);
  const [draft, setDraft] = useState<DashboardData>(defaults);
  const [notice, setNotice] = useState("Carregando dados…");
  const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/dashboard").then(r => r.ok ? r.json() : Promise.reject()).then(result => {
    const next = normalise(result.data); setData(next); setDraft(next); setNotice(result.data ? "Dados sincronizados" : "Use Entrada de dados para começar");
  }).catch(() => setNotice("Não foi possível sincronizar os dados")); }, []);

  const growth = data.previousRevenue > 0 ? (data.revenue-data.previousRevenue)/data.previousRevenue*100 : 0;
  const goal = data.target > 0 ? data.revenue/data.target*100 : 0;
  const conversion = data.proposals >= data.negotiations && data.negotiations >= data.closings && data.proposals > 0 ? data.closings/data.proposals*100 : Number.NaN;
  const recommendation = useMemo(() => recommendationFor(data), [data]);
  const funnelValid = draft.proposals >= draft.negotiations && draft.negotiations >= draft.closings;

  async function persist(next: DashboardData, success = "Alterações salvas") {
    setSaving(true); setNotice("Salvando…");
    try { const response = await fetch("/api/dashboard", { method:"PUT", headers:{"Content-Type":"application/json"}, body:JSON.stringify(next) }); if (!response.ok) throw new Error(); setData(next); setDraft(next); setNotice(success); return true; }
    catch { setNotice("Não foi possível salvar. Tente novamente."); return false; } finally { setSaving(false); }
  }
  async function saveData(event: FormEvent) { event.preventDefault(); if (!funnelValid) return; const record=toPeriodRecord(draft); const current=toPeriodRecord(data); const history=draft.periods.filter(p=>p.period!==record.period&&p.period!==current.period); const next={...draft,periods:[record,...(current.period!==record.period?[current]:[]),...history]}; if (await persist(next)) setView("overview"); }
  function selectPeriod(period: string) { const record=data.periods.find(p=>p.period===period); if (!record || record.period===data.period) return; const next={...data,...record,projects:record.projects}; setData(next); setDraft(next); setNotice(`Visualizando ${period}`); }
  async function applyPlan() {
    if (data.negotiations > data.proposals || data.closings > data.negotiations) { setDraft(data); setView("data"); setNotice("Corrija o funil antes de criar um plano"); return; }
    if (data.actions.some(a => !a.done && a.title === recommendation.title)) { setView("projects"); setNotice("Este plano já está em acompanhamento"); return; }
    const action = { id: crypto.randomUUID(), title: recommendation.title, detail: recommendation.detail, done:false, createdAt:new Date().toISOString() };
    if (await persist({...data, actions:[action,...data.actions]}, "Plano criado e adicionado ao acompanhamento")) setView("projects");
  }
  async function toggleAction(id: string) { await persist({...data, actions:data.actions.map(a => a.id === id ? {...a,done:!a.done} : a)}, "Plano atualizado"); }
  const nav = (target: View,label:string,index:string) => <button className={view===target?"active":""} onClick={()=>setView(target)}><span>{index}</span>{label}</button>;
  const title = view === "overview" ? `Olá, ${data.owner.split(" ")[0]}.` : ({commercial:"Comercial",projects:"Projetos e planos",data:"Entrada de dados",reports:"Relatórios",settings:"Configurações"} as const)[view];

  return <main className="app-shell"><aside className="sidebar"><button className="logo" onClick={()=>setView("overview")}><span>DH</span><div><b>Decision Hub</b><small>Business control</small></div></button><nav aria-label="Navegação principal"><p>Análise</p>{nav("commercial","Comercial","01")}{nav("overview","Visão geral","02")}{nav("projects","Projetos e planos","03")}<p>Gestão</p>{nav("data","Entrada de dados","04")}{nav("reports","Relatórios","05")}{nav("settings","Configurações","06")}</nav><div className="sidebar-foot"><div className="avatar">{data.owner.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><b>{data.owner}</b><small>Administrador</small></div></div></aside>
  <section className="workspace"><header className="topbar"><div><p>DECISION HUB / {view.toUpperCase()}</p><h1>{title}</h1></div><div className="top-actions"><span className="sync-status">● {notice}</span><label className="period-picker"><span>Período</span><select value={data.period} onChange={e=>selectPeriod(e.target.value)}><option value={data.period}>{data.period}</option>{data.periods.filter(p=>p.period!==data.period).map(p=><option key={p.period}>{p.period}</option>)}</select></label>{!(["data","settings","reports"] as View[]).includes(view)&&<button className="export" onClick={()=>setView("data")}>Atualizar dados</button>}</div></header>
  {view==="data"?<DataEntry draft={draft} setDraft={setDraft} save={saveData} saving={saving} valid={funnelValid} cancel={()=>{setDraft(data);setView("overview")}}/>:view==="settings"?<Settings data={data} save={persist} saving={saving}/>:view==="reports"?<Reports data={data} growth={growth} goal={goal} conversion={conversion} recommendation={recommendation}/>:view==="projects"?<Projects data={data} toggleAction={toggleAction}/>:view==="commercial"?<Commercial data={data} conversion={conversion}/>:<Overview data={data} growth={growth} goal={goal} conversion={conversion} recommendation={recommendation} applyPlan={applyPlan} saving={saving}/>}<footer><span>Decision Hub · {data.company}</span><span>{notice}</span></footer></section></main>;
}

function Commercial({data,conversion}:{data:DashboardData;conversion:number}) { const valid=data.proposals>=data.negotiations&&data.negotiations>=data.closings; const negRate=data.proposals?data.negotiations/data.proposals*100:0; return <div className="view-stack"><section className="commercial-hero"><div><p>PIPELINE TOTAL</p><strong>{compactMoney(data.pipeline)}</strong><span>oportunidades qualificadas</span></div><div><p>CONVERSÃO GERAL</p><strong>{valid?pct(conversion):"Revisar dados"}</strong><span>{valid?"fechamentos sobre propostas":"funil em ordem inconsistente"}</span></div><div><p>EM NEGOCIAÇÃO</p><strong>{valid?pct(negRate):"—"}</strong><span>{data.negotiations} de {data.proposals} propostas</span></div></section><Funnel data={data}/><section className="panel empty-state"><p>OPORTUNIDADES</p><h2>Nenhuma oportunidade cadastrada.</h2><span>Cadastre negócios individuais para acompanhar cliente, valor e etapa.</span></section></div> }
function Overview({data,growth,goal,conversion,recommendation,applyPlan,saving}:{data:DashboardData;growth:number;goal:number;conversion:number;recommendation:ReturnType<typeof recommendationFor>;applyPlan:()=>void;saving:boolean}) { const attention=data.projects.filter(p=>projectHealth(p,data.marginTarget).tone==="warn").length; const valid=data.proposals>=data.negotiations&&data.negotiations>=data.closings; return <><section className={`commercial-strip ${valid?"":"data-warning"}`}><div><p>COMERCIAL</p><h2>{data.proposals} propostas <span>→</span> {data.negotiations} negociações <span>→</span> {data.closings} fechamentos</h2></div><div><strong>{valid?pct(conversion):"Dados inválidos"}</strong><span>{valid?"conversão":"corrija o funil"}</span></div><div><strong>{compactMoney(data.pipeline)}</strong><span>pipeline</span></div></section><section className="hero-metric"><div className="revenue"><p>Receita reconhecida no mês</p><div><strong>{compactMoney(data.revenue)}</strong><span className={growth>=0?"positive":"negative"}>{growth>=0?"↗":"↘"} {pct(Math.abs(growth))}</span></div><small>{money(Math.abs(data.revenue-data.previousRevenue))} {growth>=0?"acima":"abaixo"} do mês anterior</small></div><div className="goal"><div><p>Meta mensal</p><b>{compactMoney(data.target)}</b></div><div className="goal-track"><span style={{width:`${clamp(goal)}%`}}/></div><small>{pct(goal)} alcançado · {goal>=100?"meta atingida":`faltam ${compactMoney(data.target-data.revenue)}`}</small></div></section><section className="metric-row">{[["Margem operacional",pct(data.margin),`Meta ${pct(data.marginTarget)}`],["Pipeline ponderado",compactMoney(data.pipeline),"Próximos 90 dias"],["Utilização da equipe",pct(data.utilization),`Meta ${pct(data.utilizationTarget)}`],["Projetos ativos",String(data.projects.length),`${attention} em atenção`]].map(m=><article key={m[0]}><p>{m[0]}</p><strong>{m[1]}</strong><small>{m[2]}</small></article>)}</section><section className="recommendation"><div className="rec-index">01</div><div><p>RECOMENDAÇÃO CALCULADA</p><h2>{recommendation.title}</h2><span>{recommendation.detail}</span></div><div className="rec-impact"><p>FOCO</p><strong>{recommendation.impact}</strong></div><button onClick={applyPlan} disabled={saving}>{saving?"Salvando…":valid?"Criar plano":"Corrigir dados"}<span>→</span></button></section><div className="dashboard-grid"><RevenueChart data={data}/><Funnel data={data}/></div><ProjectTable data={data} compact/></> }
function Funnel({data}:{data:DashboardData}) { const steps:[[string,number],[string,number],[string,number]]=[["Propostas",data.proposals],["Negociação",data.negotiations],["Fechamento",data.closings]]; const valid=data.proposals>=data.negotiations&&data.negotiations>=data.closings; return <section className={`panel funnel ${valid?"":"invalid-funnel"}`}><header><div><p>PIPELINE COMERCIAL</p><h2>{valid?"Conversão do funil":"Funil precisa de correção"}</h2></div></header><div className="funnel-total"><strong>{compactMoney(data.pipeline)}</strong><span>pipeline ponderado</span></div>{steps.map(([label,value])=>{const rate=data.proposals?value/data.proposals*100:0;return <div className="funnel-row" key={label}><span>{label}</span><b>{value}</b><i style={{width:`${valid?clamp(rate):0}%`}}/><small>{valid?pct(rate):"revisar"}</small></div>})}</section> }
function RevenueChart({data}:{data:DashboardData}) { const scale=Math.max(data.target,data.revenue,1); const actual=[.62,.68,.65,.78,.84,1].map(x=>data.revenue*x); return <section className="panel revenue-chart"><header><div><p>DESEMPENHO FINANCEIRO</p><h2>Receita × meta</h2></div></header><div className="chart-area"><div className="axis"><span>{compactMoney(scale)}</span><span>{compactMoney(scale*.66)}</span><span>{compactMoney(scale*.33)}</span><span>R$ 0</span></div><div className="bars">{actual.map((value,i)=><div className="month" key={i}><div className="bar-pair"><i style={{height:`${clamp(data.target/scale*88)}%`}}/><b style={{height:`${clamp(value/scale*88)}%`}}/></div><span>{["Fev","Mar","Abr","Mai","Jun","Jul"][i]}</span></div>)}</div></div></section> }
function ProjectTable({data,compact=false}:{data:DashboardData;compact?:boolean}) { return <section className="panel project-panel"><header><div><p>PORTFÓLIO DE ENTREGAS</p><h2>{compact?"Projetos que exigem leitura":"Todos os projetos"}</h2></div></header><div className="project-head"><span>Projeto / Cliente</span><span>Progresso</span><span>Margem</span><span>Equipe</span><span>Status calculado</span></div>{data.projects.map(p=>{const health=projectHealth(p,data.marginTarget);return <article className="project-row" key={p.id}><div><b>{p.name}</b><small>{p.client}</small></div><div className="progress"><span><i style={{width:`${clamp(p.progress)}%`}}/></span><b>{pct(p.progress)}</b></div><strong>{pct(p.margin)}</strong><span>{p.team} pessoas</span><em className={health.tone}>{health.label}</em></article>})}</section> }
function Projects({data,toggleAction}:{data:DashboardData;toggleAction:(id:string)=>void}) { return <div className="view-stack"><section className="panel action-panel"><header><div><p>PLANO DE AÇÃO</p><h2>Acompanhamento das decisões</h2></div><span>{data.actions.filter(a=>!a.done).length} abertas</span></header>{data.actions.length===0?<div className="empty-state"><b>Nenhum plano criado.</b><span>Use “Criar plano” na recomendação da Visão geral.</span></div>:data.actions.map(a=><article className={a.done?"done":""} key={a.id}><button onClick={()=>toggleAction(a.id)} aria-label={a.done?"Reabrir plano":"Concluir plano"}>{a.done?"✓":""}</button><div><b>{a.title}</b><small>{a.detail}</small></div><time>{new Date(a.createdAt).toLocaleDateString("pt-BR")}</time></article>)}</section><ProjectTable data={data}/></div> }
function Reports({data,growth,goal,conversion,recommendation}:{data:DashboardData;growth:number;goal:number;conversion:number;recommendation:ReturnType<typeof recommendationFor>}) { const [scope,setScope]=useState("executive"); const downloadCsv=()=>{const rows=[["Indicador","Valor"],["Receita",data.revenue],["Meta",data.target],["Margem",data.margin],["Pipeline",data.pipeline],["Utilização",data.utilization],["Propostas",data.proposals],["Negociações",data.negotiations],["Fechamentos",data.closings]];const blob=new Blob([rows.map(r=>r.join(";")).join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`decision-hub-${data.period.toLowerCase().replaceAll(" ","-")}.csv`;a.click();URL.revokeObjectURL(url)}; return <div className="view-stack report-view"><section className="report-toolbar"><label>Tipo de relatório<select value={scope} onChange={e=>setScope(e.target.value)}><option value="executive">Executivo</option><option value="commercial">Comercial</option><option value="projects">Projetos</option></select></label><button onClick={downloadCsv}>Exportar CSV</button><button className="primary" onClick={()=>window.print()}>Imprimir / salvar PDF</button></section><section className="report-cover"><p>RELATÓRIO {scope==="executive"?"EXECUTIVO":scope==="commercial"?"COMERCIAL":"DE PROJETOS"}</p><h2>{data.company}</h2><span>{data.period} · dados consolidados do Decision Hub</span></section><section className="report-summary">{[["Receita",compactMoney(data.revenue)],["Crescimento",pct(growth)],["Meta atingida",pct(goal)],["Conversão",pct(conversion)]].map(x=><article key={x[0]}><p>{x[0]}</p><strong>{x[1]}</strong></article>)}</section>{scope!=="projects"&&<section className="panel report-text"><article><h2>Leitura executiva</h2><p>A receita alcançou {compactMoney(data.revenue)}, equivalente a {pct(goal)} da meta. O pipeline é de {compactMoney(data.pipeline)}, com conversão de {pct(conversion)}.</p></article><article><h3>Recomendação calculada</h3><p><b>{recommendation.title}</b> {recommendation.detail}</p></article></section>}{scope!=="commercial"&&<ProjectTable data={data}/>}</div> }
function DataEntry({draft,setDraft,save,saving,valid,cancel}:{draft:DashboardData;setDraft:(d:DashboardData)=>void;save:(e:FormEvent)=>void;saving:boolean;valid:boolean;cancel:()=>void}) {
  const field=(key:keyof DashboardData,label:string,type="number")=><label><span>{label}</span><input type={type} min={type==="number"?0:undefined} value={String(draft[key])} onChange={e=>setDraft({...draft,[key]:type==="number"?Number(e.target.value):e.target.value})}/></label>;
  const projectField=(id:string,key:keyof Project,value:string|number,type="text")=><input aria-label={`${key} do projeto`} type={type} min={type==="number"?0:undefined} max={key==="progress"?100:undefined} value={value} onChange={e=>setDraft({...draft,projects:draft.projects.map(p=>p.id===id?{...p,[key]:type==="number"?Number(e.target.value):e.target.value}:p)})}/>;
  const addProject=()=>setDraft({...draft,projects:[...draft.projects,{id:crypto.randomUUID(),name:"Novo projeto",client:"Cliente",progress:0,margin:draft.marginTarget,team:1}]});
  const removeProject=(id:string)=>setDraft({...draft,projects:draft.projects.filter(p=>p.id!==id)});
  return <form className="settings-view" onSubmit={save}><section className="settings-intro"><div><p>INDICADORES DO PERÍODO</p><h2>Atualize os dados operacionais.</h2><span>O funil é validado antes de salvar.</span></div></section><section className="settings-grid"><fieldset><legend>Período e financeiro</legend>{field("period","Período","text")}{field("revenue","Receita do mês (R$)")}{field("previousRevenue","Receita anterior (R$)")}{field("target","Meta mensal (R$)")}{field("margin","Margem operacional (%)")}</fieldset><fieldset className={!valid?"invalid":""}><legend>Comercial e capacidade</legend>{field("pipeline","Pipeline ponderado (R$)")}{field("utilization","Utilização da equipe (%)")}{field("proposals","Propostas")}{field("negotiations","Negociações")}{field("closings","Fechamentos")}{!valid&&<p className="field-error">Use a ordem correta: propostas ≥ negociações ≥ fechamentos.</p>}</fieldset></section><section className="panel project-editor"><header><div><p>PROJETOS</p><h2>Portfólio do período</h2></div><button type="button" className="add-project" onClick={addProject}>+ Adicionar projeto</button></header><div className="project-edit-head"><span>Projeto</span><span>Cliente</span><span>Progresso %</span><span>Margem %</span><span>Equipe</span><span></span></div>{draft.projects.map(p=><div className="project-edit-row" key={p.id}>{projectField(p.id,"name",p.name)}{projectField(p.id,"client",p.client)}{projectField(p.id,"progress",p.progress,"number")}{projectField(p.id,"margin",p.margin,"number")}{projectField(p.id,"team",p.team,"number")}<button type="button" className="remove-project" onClick={()=>removeProject(p.id)} aria-label={`Remover ${p.name}`}>Remover</button></div>)}{draft.projects.length===0&&<div className="empty-state"><b>Nenhum projeto neste período.</b></div>}</section><div className="settings-actions"><button type="button" onClick={cancel}>Cancelar</button><button className="save" disabled={saving||!valid}>{saving?"Salvando…":"Salvar dados do período"}</button></div></form>
}
function Settings({data,save,saving}:{data:DashboardData;save:(d:DashboardData,s?:string)=>Promise<boolean>;saving:boolean}) {
  const [draft,setDraft]=useState(data); const submit=async(e:FormEvent)=>{e.preventDefault();await save(draft,"Configurações atualizadas")};
  return <form className="settings-view" onSubmit={submit}><section className="settings-intro"><div><p>CONFIGURAÇÕES</p><h2>Regras do negócio e dos relatórios.</h2><span>As metas abaixo determinam alertas, status e recomendações.</span></div></section><section className="settings-grid"><fieldset><legend>Empresa</legend><label><span>Nome da empresa</span><input value={draft.company} onChange={e=>setDraft({...draft,company:e.target.value})}/></label><label><span>Segmento</span><input value={draft.segment} onChange={e=>setDraft({...draft,segment:e.target.value})}/></label><label><span>Responsável pelo workspace</span><input value={draft.owner} onChange={e=>setDraft({...draft,owner:e.target.value})}/></label><label><span>E-mail para alertas</span><input type="email" placeholder="gestao@empresa.com" value={draft.notificationEmail} onChange={e=>setDraft({...draft,notificationEmail:e.target.value})}/></label></fieldset><fieldset><legend>Metas e alertas</legend><label><span>Meta de margem (%)</span><input type="number" min="0" max="100" value={draft.marginTarget} onChange={e=>setDraft({...draft,marginTarget:Number(e.target.value)})}/></label><label><span>Meta de utilização (%)</span><input type="number" min="0" max="100" value={draft.utilizationTarget} onChange={e=>setDraft({...draft,utilizationTarget:Number(e.target.value)})}/></label></fieldset><fieldset className="wide"><legend>Relatórios</legend><label><span>Nota padrão do rodapé</span><input value={draft.reportNote} onChange={e=>setDraft({...draft,reportNote:e.target.value})}/></label></fieldset><fieldset className="wide access-info"><legend>Equipe e acesso</legend><p>O acesso atual é controlado pela hospedagem. Perfis com papéis diferentes exigem autenticação própria; a opção gratuita recomendada é Supabase Auth.</p><span>Estrutura prevista: Administrador gerencia usuários e configurações; Usuário edita dados; Leitor apenas consulta e exporta.</span></fieldset></section><div className="settings-actions"><button type="button" onClick={()=>setDraft(data)}>Descartar</button><button className="save" disabled={saving}>{saving?"Salvando…":"Salvar configurações"}</button></div></form>
}
